import crypto from "crypto";

export default async function handler(req, res) {
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    try {
        const { 
            paymentMode, 
            razorpay_payment_id, 
            orderData 
        } = req.body;

        const dbUrl = "https://iskcon-food-default-rtdb.firebaseio.com/orders.json";
        const botToken = process.env.TELEGRAM_ORDERS_BOT;
        const chatId = process.env.TELEGRAM_ORDERS_CHAT_ID;
        const rzpId = process.env.RAZORPAY_KEY_ID;
        const rzpSecret = process.env.RAZORPAY_KEY_SECRET;

        // 1. ONLINE PAYMENT SECURITY CHECK
        if (paymentMode === 'Online') {
            if (!razorpay_payment_id) {
                return res.status(400).json({ error: 'Missing Razorpay Payment ID' });
            }

            // Secure Server-to-Server Verification using Razorpay's Official Fetch API
            const authHeader = 'Basic ' + Buffer.from(rzpId + ':' + rzpSecret).toString('base64');
            const rzpRes = await fetch(`https://api.razorpay.com/v1/payments/${razorpay_payment_id}`, {
                headers: { 'Authorization': authHeader }
            });

            if (!rzpRes.ok) {
                await notifySecurityAlert("Invalid/Fake Payment ID used during transaction attempt", orderData);
                return res.status(400).json({ error: 'Fake Payment ID detected!' });
            }

            const rzpPayment = await rzpRes.json();
            const expectedPaise = Math.round(orderData.total * 100);

            // Double Check Status and Amount to prevent console manipulation
            const isValidStatus = rzpPayment.status === 'captured' || rzpPayment.status === 'authorized';
            const isValidAmount = Math.abs(rzpPayment.amount - expectedPaise) <= 1; // Allows 1 paise difference

            if (!isValidStatus || !isValidAmount) {
                await notifySecurityAlert(`Cheat Attempt! Status: ${rzpPayment.status}, Amount Sent: ₹${rzpPayment.amount/100}, Expected: ₹${orderData.total}`, orderData);
                return res.status(400).json({ error: 'Payment amount or status mismatch. Tampering detected!' });
            }

            // If verified successfully, attach credentials securely
            orderData.paymentId = razorpay_payment_id;
            orderData.status = 'placed';
        } else {
            // For COD payments
            orderData.status = 'placed';
        }

        // Add standard timestamp
        orderData.createdAt = Date.now();

        // 2. SECURE DB WRITE (Directly to Firebase via REST API)
        const firebaseRes = await fetch(dbUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(orderData)
        });

        if (!firebaseRes.ok) {
            throw new Error("Failed to write verified order to Firebase RTDB");
        }

        const firebaseData = await firebaseRes.json();
        const orderId = firebaseData.name; // Autogenerated push ID from Firebase

        // 3. SECURE TELEGRAM ORDERS BOT NOTIFICATION
        if (botToken && chatId) {
            const itemSummary = orderData.items.map(i => `• ${i.name} (${i.qty} x ₹${i.price})`).join('\n');
            const payIdStr = orderData.paymentId ? `\n<b>Razorpay Pay ID:</b> ${orderData.paymentId}` : '';
            const msg = `🔔 <b>NEW ORDER PLACED!</b>\n` +
                        `<b>Order ID:</b> #${orderId.slice(-5).toUpperCase()} (${orderId})\n` +
                        `<b>Customer Name:</b> ${orderData.userName}\n` +
                        `<b>Phone:</b> ${orderData.userPhone}\n` +
                        `<b>Address:</b> ${orderData.address}\n` +
                        `<b>Payment Mode:</b> ${orderData.paymentMode}${payIdStr}\n\n` +
                        `📦 <b>Items:</b>\n${itemSummary}\n\n` +
                        `💰 <b>Bill Details:</b>\n` +
                        `Subtotal: ₹${orderData.subTotal}\n` +
                        `Discount: ₹${orderData.discount}\n` +
                        `Delivery Fee: ₹${orderData.deliveryFee}\n` +
                        `<b>Total Paid:</b> ₹${orderData.total}`;

            await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    chat_id: chatId,
                    text: msg,
                    parse_mode: 'HTML'
                })
            });
        }

        return res.status(200).json({ success: true, orderId: orderId });

    } catch (error) {
        console.error("Order processing error:", error);
        return res.status(500).json({ error: error.message });
    }
}

// Inner helper to notify leads bot about failed backend verifications/cheat attempts
async function notifySecurityAlert(reason, orderData) {
    const leadsBot = process.env.TELEGRAM_LEADS_BOT;
    const leadsChat = process.env.TELEGRAM_LEADS_CHAT_ID;
    if (!leadsBot || !leadsChat) return;

    const itemsStr = orderData.items.map(i => `• ${i.name} (${i.qty} x ₹${i.price})`).join('\n');
    const msg = `🚨 <b>TAMPER WARNING / SECURE CHECKOUT ALERT!</b>\n` +
                `<b>Reason:</b> ${reason}\n` +
                `<b>Customer Name:</b> ${orderData.userName}\n` +
                `<b>Phone:</b> <a href="tel:${orderData.userPhone}">${orderData.userPhone}</a>\n` +
                `<b>Cart Summary:</b>\n${itemsStr}\n` +
                `<b>Total expected amount:</b> ₹${orderData.total}`;

    await fetch(`https://api.telegram.org/bot${leadsBot}/sendMessage`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            chat_id: leadsChat,
            text: msg,
            parse_mode: 'HTML'
        })
    }).catch(e => console.error(e));
}
